language: node_js
node_js:
- 14
cache: npm

install: skip

script: skip

before_deploy:
- cd client

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: main
