language: node_js
node_js:
- 14
- node
cache: npm

install:
- npm ci

script:
- npm test
- npm run build

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  on:
  repo: lukmanmemon/GameShop
